Assignment expressions? Not a chance!
1. Now we have two (2) kinds of assignments, '=' and ':='
   And Guido says PEP-20 is not true because it "can't prove everything."
   Yep. PEP-20 is true as often as Guido needs it to argue for his side,
   and vice versa.

2. assert 0 == (x := (y := (z := 0)))

What the actual fuck!? This PEP is copying the ugliest part of C into
Python. And just because JavaScipt does this, it doesn't help support this
shitty PEP.

Do you ever know the 2003 Linux backdoor attempt?

    if (uid = 0):
        # BOOM!!!

If I write this in Python

    x = 100
    if x = 0:

Python will yell at me:

    File "<stdin>", line 1
      if x = 0:
           ^
    SyntaxError: invalid syntax

This is a live-saving feature.

If := is encouraged to be used in loops and flow-control statements, I
firmly believe shit like (current->uid = 0) will happen sooner in the
Python world.

3. People are yelling, screaming, complaining,
   "Fuck no"
   "I really really don't like this idea."
   "I find this ridiculous on its face -- I do not accept that the cost
   of introducing this very ugly operator is at all justified by the
   benefits."

Don't you hear that?!

https://old.reddit.com/r/Python/comments/8ex72p/pep_572_assignment_expressions/

I am very disappointed that Python developers are falling into the
circlejerk of their own assumptions. Python DEVELOPERS are ATYPICAL users.
You must listen to the Python USERS. You must listen to a VARIETY of
Python users.

If Python sucks next year, I will not blame the Python users for not
telling you about such problematic design decisions. I will blame you,
Guido and other Python developers for not listening.

Your most hated,
'pep-20-supporter